apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nusaroute
spec:
  ports:
  - name: db
    port: 5432
    targetPort: 5433
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: nusaroute
subsets:
- addresses:
  - ip: 192.168.65.254
  ports:
  - name: db
    port: 5433
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nusaroute
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: nusaroute
subsets:
- addresses:
  - ip: 192.168.65.254
  ports:
  - name: redis
    port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: nusaroute
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
  namespace: nusaroute
subsets:
- addresses:
  - ip: 192.168.65.254
  ports:
  - name: mongodb
    port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: nusaroute
spec:
  ports:
  - name: kafka-9092
    port: 9092
    targetPort: 29092
  - name: kafka-29092
    port: 29092
    targetPort: 29092
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka
  namespace: nusaroute
subsets:
- addresses:
  - ip: 192.168.65.254
  ports:
  - name: kafka-9092
    port: 29092
  - name: kafka-29092
    port: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: nusaroute
spec:
  ports:
  - name: minio
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio
  namespace: nusaroute
subsets:
- addresses:
  - ip: 192.168.65.254
  ports:
  - name: minio
    port: 9000
