// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/courier/courier.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourierLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierLocationRequest) Reset() {
	*x = CourierLocationRequest{}
	mi := &file_api_proto_courier_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierLocationRequest) ProtoMessage() {}

func (x *CourierLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierLocationRequest.ProtoReflect.Descriptor instead.
func (*CourierLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_courier_proto_rawDescGZIP(), []int{0}
}

func (x *CourierLocationRequest) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

type CourierLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierLocationResponse) Reset() {
	*x = CourierLocationResponse{}
	mi := &file_api_proto_courier_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierLocationResponse) ProtoMessage() {}

func (x *CourierLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierLocationResponse.ProtoReflect.Descriptor instead.
func (*CourierLocationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_courier_proto_rawDescGZIP(), []int{1}
}

func (x *CourierLocationResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CourierLocationResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CourierLocationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AvailableCouriersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableCouriersRequest) Reset() {
	*x = AvailableCouriersRequest{}
	mi := &file_api_proto_courier_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableCouriersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCouriersRequest) ProtoMessage() {}

func (x *AvailableCouriersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCouriersRequest.ProtoReflect.Descriptor instead.
func (*AvailableCouriersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_courier_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableCouriersRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AvailableCouriersRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AvailableCouriersRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type CourierInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	CurrentLat    float64                `protobuf:"fixed64,4,opt,name=current_lat,json=currentLat,proto3" json:"current_lat,omitempty"`
	CurrentLng    float64                `protobuf:"fixed64,5,opt,name=current_lng,json=currentLng,proto3" json:"current_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierInfo) Reset() {
	*x = CourierInfo{}
	mi := &file_api_proto_courier_courier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierInfo) ProtoMessage() {}

func (x *CourierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_courier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierInfo.ProtoReflect.Descriptor instead.
func (*CourierInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_courier_proto_rawDescGZIP(), []int{3}
}

func (x *CourierInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourierInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CourierInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CourierInfo) GetCurrentLat() float64 {
	if x != nil {
		return x.CurrentLat
	}
	return 0
}

func (x *CourierInfo) GetCurrentLng() float64 {
	if x != nil {
		return x.CurrentLng
	}
	return 0
}

type AvailableCouriersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CourierInfo         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableCouriersResponse) Reset() {
	*x = AvailableCouriersResponse{}
	mi := &file_api_proto_courier_courier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableCouriersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCouriersResponse) ProtoMessage() {}

func (x *AvailableCouriersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_courier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCouriersResponse.ProtoReflect.Descriptor instead.
func (*AvailableCouriersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_courier_proto_rawDescGZIP(), []int{4}
}

func (x *AvailableCouriersResponse) GetData() []*CourierInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_proto_courier_courier_proto protoreflect.FileDescriptor

const file_api_proto_courier_courier_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/courier/courier.proto\x12\acourier\"7\n" +
	"\x16CourierLocationRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\"k\n" +
	"\x17CourierLocationResponse\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"q\n" +
	"\x18AvailableCouriersRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\"\x92\x01\n" +
	"\vCourierInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1f\n" +
	"\vcurrent_lat\x18\x04 \x01(\x01R\n" +
	"currentLat\x12\x1f\n" +
	"\vcurrent_lng\x18\x05 \x01(\x01R\n" +
	"currentLng\"E\n" +
	"\x19AvailableCouriersResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.courier.CourierInfoR\x04data2\xcc\x01\n" +
	"\x0eCourierService\x12Y\n" +
	"\x12GetCourierLocation\x12\x1f.courier.CourierLocationRequest\x1a .courier.CourierLocationResponse\"\x00\x12_\n" +
	"\x14GetAvailableCouriers\x12!.courier.AvailableCouriersRequest\x1a\".courier.AvailableCouriersResponse\"\x00B;Z9github.com/nusaroute/services/courier-service/pkg/grpc/pbb\x06proto3"

var (
	file_api_proto_courier_courier_proto_rawDescOnce sync.Once
	file_api_proto_courier_courier_proto_rawDescData []byte
)

func file_api_proto_courier_courier_proto_rawDescGZIP() []byte {
	file_api_proto_courier_courier_proto_rawDescOnce.Do(func() {
		file_api_proto_courier_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_courier_courier_proto_rawDesc), len(file_api_proto_courier_courier_proto_rawDesc)))
	})
	return file_api_proto_courier_courier_proto_rawDescData
}

var file_api_proto_courier_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_courier_courier_proto_goTypes = []any{
	(*CourierLocationRequest)(nil),    // 0: courier.CourierLocationRequest
	(*CourierLocationResponse)(nil),   // 1: courier.CourierLocationResponse
	(*AvailableCouriersRequest)(nil),  // 2: courier.AvailableCouriersRequest
	(*CourierInfo)(nil),               // 3: courier.CourierInfo
	(*AvailableCouriersResponse)(nil), // 4: courier.AvailableCouriersResponse
}
var file_api_proto_courier_courier_proto_depIdxs = []int32{
	3, // 0: courier.AvailableCouriersResponse.data:type_name -> courier.CourierInfo
	0, // 1: courier.CourierService.GetCourierLocation:input_type -> courier.CourierLocationRequest
	2, // 2: courier.CourierService.GetAvailableCouriers:input_type -> courier.AvailableCouriersRequest
	1, // 3: courier.CourierService.GetCourierLocation:output_type -> courier.CourierLocationResponse
	4, // 4: courier.CourierService.GetAvailableCouriers:output_type -> courier.AvailableCouriersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_courier_courier_proto_init() }
func file_api_proto_courier_courier_proto_init() {
	if File_api_proto_courier_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_courier_courier_proto_rawDesc), len(file_api_proto_courier_courier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_courier_courier_proto_goTypes,
		DependencyIndexes: file_api_proto_courier_courier_proto_depIdxs,
		MessageInfos:      file_api_proto_courier_courier_proto_msgTypes,
	}.Build()
	File_api_proto_courier_courier_proto = out.File
	file_api_proto_courier_courier_proto_goTypes = nil
	file_api_proto_courier_courier_proto_depIdxs = nil
}
