apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    {{- if .Values.global.istioInjection }}
    istio-injection: enabled
    {{- end }}
