apiVersion: v1
kind: Secret
metadata:
  name: nusaroute-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  db-user: {{ .Values.secrets.dbUser | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  mongo-uri: {{ .Values.secrets.mongoUri | quote }}
